### ISSUE TITLE
WiFi?

### ISSUE THREAD

**Issue by 532910** [andrei-tatar/imagotag-hack#8]
TI says CC2510 has 2.4 GHz radio transceiver, but standard is "Proprietary".

Why readme  says "CC2510 - MCU + WiFi - 8051"?
Is there any reason to hack this tags if radio standard is "proprietary"?

**Comment by andrei-tatar** [comment]
@532910 I removed `WiFi` from the readme, replaced it with `radio`.

> Is there any reason to hack this tags if radio standard is "proprietary"?

There is open source firmware that uses the radio for CC2510. (https://github.com/fishpepper/OpenSky) so a new firmware could be used to provide some custom functionality.

**Comment by 532910** [comment]
I'd suggest to replace it with "2.4GHz proprietary radio"
